version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# This will make RTD use your default branch
python:
  install:
    - requirements: requirements.txt  # adjust if your requirements file is elsewhere

sphinx:
  configuration: conf.py  # adjust path to your conf.py file
