# WicdPico Standalone Sensor Meter Configuration
# Dedicated AP mode for I2C sensor monitoring

# WiFi Access Point Configuration
WIFI_SSID = "PicoTest-Node00"
WIFI_PASSWORD = "testpass123"
WIFI_MODE = "AP"

# System Configuration
BLINK_INTERVAL = "0.5"